-   id: theme-check
    name: theme-check
    entry: theme-check --auto-correct
    language: ruby
    'types': [file]
    files: \.liquid$
    args: []
    require_serial: false
    additional_dependencies: []